/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Generated.Client.OpenAPIDateConverter;

namespace Tribufu.Generated.Model
{
    /// <summary>
    /// Defines CodeChallengeMethod
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CodeChallengeMethod
    {
        /// <summary>
        /// Enum Plain for value: plain
        /// </summary>
        [EnumMember(Value = "plain")]
        Plain,

        /// <summary>
        /// Enum S256 for value: S256
        /// </summary>
        [EnumMember(Value = "S256")]
        S256
    }

}
