/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Generated.Client.OpenAPIDateConverter;

namespace Tribufu.Generated.Model
{
    /// <summary>
    /// CryptoViewModel
    /// </summary>
    [DataContract(Name = "CryptoViewModel")]
    public partial class CryptoViewModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptoViewModel" /> class.
        /// </summary>
        /// <param name="encoded">encoded.</param>
        /// <param name="decoded">decoded.</param>
        public CryptoViewModel(string encoded = default(string), string decoded = default(string))
        {
            this.Encoded = encoded;
            this.Decoded = decoded;
        }

        /// <summary>
        /// Gets or Sets Encoded
        /// </summary>
        [DataMember(Name = "encoded", EmitDefaultValue = true)]
        public string Encoded { get; set; }

        /// <summary>
        /// Gets or Sets Decoded
        /// </summary>
        [DataMember(Name = "decoded", EmitDefaultValue = true)]
        public string Decoded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CryptoViewModel {\n");
            sb.Append("  Encoded: ").Append(Encoded).Append("\n");
            sb.Append("  Decoded: ").Append(Decoded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
