/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Generated.Client.OpenAPIDateConverter;

namespace Tribufu.Generated.Model
{
    /// <summary>
    /// Defines GrantType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GrantType
    {
        /// <summary>
        /// Enum AuthorizationCode for value: authorization_code
        /// </summary>
        [EnumMember(Value = "authorization_code")]
        AuthorizationCode,

        /// <summary>
        /// Enum ClientCredentials for value: client_credentials
        /// </summary>
        [EnumMember(Value = "client_credentials")]
        ClientCredentials,

        /// <summary>
        /// Enum Password for value: password
        /// </summary>
        [EnumMember(Value = "password")]
        Password,

        /// <summary>
        /// Enum RefreshToken for value: refresh_token
        /// </summary>
        [EnumMember(Value = "refresh_token")]
        RefreshToken
    }

}
