/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Generated.Client.OpenAPIDateConverter;

namespace Tribufu.Generated.Model
{
    /// <summary>
    /// Defines LoginProvider
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LoginProvider
    {
        /// <summary>
        /// Enum Steam for value: steam
        /// </summary>
        [EnumMember(Value = "steam")]
        Steam,

        /// <summary>
        /// Enum Epic for value: epic
        /// </summary>
        [EnumMember(Value = "epic")]
        Epic,

        /// <summary>
        /// Enum Discord for value: discord
        /// </summary>
        [EnumMember(Value = "discord")]
        Discord,

        /// <summary>
        /// Enum Microsoft for value: microsoft
        /// </summary>
        [EnumMember(Value = "microsoft")]
        Microsoft,

        /// <summary>
        /// Enum Playstation for value: playstation
        /// </summary>
        [EnumMember(Value = "playstation")]
        Playstation,

        /// <summary>
        /// Enum Google for value: google
        /// </summary>
        [EnumMember(Value = "google")]
        Google,

        /// <summary>
        /// Enum Apple for value: apple
        /// </summary>
        [EnumMember(Value = "apple")]
        Apple
    }

}
