/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Client.OpenAPIDateConverter;

namespace Tribufu.Model
{
    /// <summary>
    /// IntrospectRequest
    /// </summary>
    [DataContract(Name = "IntrospectRequest")]
    public partial class IntrospectRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TokenTypeHint
        /// </summary>
        [DataMember(Name = "token_type_hint", EmitDefaultValue = false)]
        public TokenHintType? TokenTypeHint { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="IntrospectRequest" /> class.
        /// </summary>
        /// <param name="token">token.</param>
        /// <param name="tokenTypeHint">tokenTypeHint.</param>
        public IntrospectRequest(string token = default(string), TokenHintType? tokenTypeHint = default(TokenHintType?))
        {
            this.Token = token;
            this.TokenTypeHint = tokenTypeHint;
        }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = true)]
        public string Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IntrospectRequest {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenTypeHint: ").Append(TokenTypeHint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
