/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribufu.Client.OpenAPIDateConverter;

namespace Tribufu.Model
{
    /// <summary>
    /// Defines TokenHintType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TokenHintType
    {
        /// <summary>
        /// Enum AccessToken for value: access_token
        /// </summary>
        [EnumMember(Value = "access_token")]
        AccessToken,

        /// <summary>
        /// Enum RefreshToken for value: refresh_token
        /// </summary>
        [EnumMember(Value = "refresh_token")]
        RefreshToken
    }

}
